### PR TITLE
Updated Pimple's version

### PR DESCRIPTION
**Pull request by mnapoli**
Pimple is v3.0 now, and I need to write a library that is compatible with that version :)

### CODE REVIEW

**Comment by moufmouf** [comment]
Oops, I don't think it is as easy as modifying Pimple's version number :)

This would break the delegate lookup feature. We need to rewrite the offsetGet method since it was greatly modified in Pimple 3. I don't have time to change this right now, do you wan't to take a look?

**Comment by mnapoli** [comment]
Hey yeah absolutely I will have a look!

**Comment by mnapoli** [comment]
Damn not easy actually! The thing is that in Pimple 3 all properties have gone private, so I don't see a way to do the delegate lookup feature (i.e. inject the parent container instead of `$this` when resolving factories)… The only solution I see is like rewriting the whole thing…

Maybe you see an obvious solution that I'm missing? I'm good with Pimple v1 actually but for sure it would be good to have an adapter for the latest version…

**Comment by moufmouf** [comment]
Ho, now that you said it, I remember I tried and stumbled on the same problem. It's almost impossible without rewriting entirely Pimple.

Or we could do something really ugly and use [`ReflectionProperty::setAccessible`](http://php.net/manual/en/reflectionproperty.setaccessible.php) to bypass the private status. Or we could submit a pull request to make the property "protected", but I'm not sure they will like it... any other thought?

**Comment by mnapoli** [comment]
I think the best solution would be to rewrite Pimple :(

Reading the private property has serious risks of breaking, they switched the properties to private for a reason. Even though the logic is quite simple they spent a lot of effort to optimize Pimple, so maybe at some point they'll change the properties for a faster internal implementation, and this wrapper will break.

The thing is that a Pimple adapter for ContainerInterface is dead simple (and that's what I need). The support for the delegate lookup feature is the problem. I could use Acclimate though…

**Comment by mnapoli** [comment]
Cleaning up my pending PRs 😄

**Pull request closed without merging**
